/**
 * Hardcoded Al-Fatiha data
 * Auto-generated by scripts/fetch-al-fatiha.ts
 * Last updated: 2025-12-25T20:42:05.659Z
 *
 * This data is permanently cached so Al-Fatiha loads instantly without any API calls.
 * All other surahs use the normal API caching mechanism.
 */

import type { VerseData } from "@/types";

export const AL_FATIHA_VERSES: VerseData[] = [
  {
    "number": 1,
    "arabicText": "بِسۡمِ ٱللَّهِ ٱلرَّحۡمَٰنِ ٱلرَّحِيمِ",
    "arabicTextQpcV2": "ﱁ ﱂ ﱃ ﱄ",
    "translationText": "In the name of Allah, the Entirely Merciful, the Especially Merciful.",
    "pageNumber": 1,
    "words": [
      {
        "id": 1,
        "position": 1,
        "pageNumber": 1,
        "codeV2": "ﱁ",
        "textQpcHafs": "بِسۡمِ",
        "charTypeName": "word"
      },
      {
        "id": 2,
        "position": 2,
        "pageNumber": 1,
        "codeV2": "ﱂ",
        "textQpcHafs": "ٱللَّهِ",
        "charTypeName": "word"
      },
      {
        "id": 3,
        "position": 3,
        "pageNumber": 1,
        "codeV2": "ﱃ",
        "textQpcHafs": "ٱلرَّحۡمَٰنِ",
        "charTypeName": "word"
      },
      {
        "id": 4,
        "position": 4,
        "pageNumber": 1,
        "codeV2": "ﱄ",
        "textQpcHafs": "ٱلرَّحِيمِ",
        "charTypeName": "word"
      },
      {
        "id": 5,
        "position": 5,
        "pageNumber": 1,
        "codeV2": "ﱅ",
        "textQpcHafs": "١",
        "charTypeName": "end"
      }
    ]
  },
  {
    "number": 2,
    "arabicText": "ٱلۡحَمۡدُ لِلَّهِ رَبِّ ٱلۡعَٰلَمِينَ",
    "arabicTextQpcV2": "ﱆ ﱇ ﱈ ﱉ",
    "translationText": "All praise is due to Allah, Lord of the worlds -",
    "pageNumber": 1,
    "words": [
      {
        "id": 1130,
        "position": 1,
        "pageNumber": 1,
        "codeV2": "ﱆ",
        "textQpcHafs": "ٱلۡحَمۡدُ",
        "charTypeName": "word"
      },
      {
        "id": 1131,
        "position": 2,
        "pageNumber": 1,
        "codeV2": "ﱇ",
        "textQpcHafs": "لِلَّهِ",
        "charTypeName": "word"
      },
      {
        "id": 1132,
        "position": 3,
        "pageNumber": 1,
        "codeV2": "ﱈ",
        "textQpcHafs": "رَبِّ",
        "charTypeName": "word"
      },
      {
        "id": 1133,
        "position": 4,
        "pageNumber": 1,
        "codeV2": "ﱉ",
        "textQpcHafs": "ٱلۡعَٰلَمِينَ",
        "charTypeName": "word"
      },
      {
        "id": 1134,
        "position": 5,
        "pageNumber": 1,
        "codeV2": "ﱊ",
        "textQpcHafs": "٢",
        "charTypeName": "end"
      }
    ]
  },
  {
    "number": 3,
    "arabicText": "ٱلرَّحۡمَٰنِ ٱلرَّحِيمِ",
    "arabicTextQpcV2": "ﱋ ﱌ",
    "translationText": "The Entirely Merciful, the Especially Merciful,",
    "pageNumber": 1,
    "words": [
      {
        "id": 2953,
        "position": 1,
        "pageNumber": 1,
        "codeV2": "ﱋ",
        "textQpcHafs": "ٱلرَّحۡمَٰنِ",
        "charTypeName": "word"
      },
      {
        "id": 2954,
        "position": 2,
        "pageNumber": 1,
        "codeV2": "ﱌ",
        "textQpcHafs": "ٱلرَّحِيمِ",
        "charTypeName": "word"
      },
      {
        "id": 2955,
        "position": 3,
        "pageNumber": 1,
        "codeV2": "ﱍ",
        "textQpcHafs": "٣",
        "charTypeName": "end"
      }
    ]
  },
  {
    "number": 4,
    "arabicText": "مَٰلِكِ يَوۡمِ ٱلدِّينِ",
    "arabicTextQpcV2": "ﱎ ﱏ ﱐ",
    "translationText": "Sovereign of the Day of Recompense.",
    "pageNumber": 1,
    "words": [
      {
        "id": 3252,
        "position": 1,
        "pageNumber": 1,
        "codeV2": "ﱎ",
        "textQpcHafs": "مَٰلِكِ",
        "charTypeName": "word"
      },
      {
        "id": 3253,
        "position": 2,
        "pageNumber": 1,
        "codeV2": "ﱏ",
        "textQpcHafs": "يَوۡمِ",
        "charTypeName": "word"
      },
      {
        "id": 3254,
        "position": 3,
        "pageNumber": 1,
        "codeV2": "ﱐ",
        "textQpcHafs": "ٱلدِّينِ",
        "charTypeName": "word"
      },
      {
        "id": 3255,
        "position": 4,
        "pageNumber": 1,
        "codeV2": "ﱑ",
        "textQpcHafs": "٤",
        "charTypeName": "end"
      }
    ]
  },
  {
    "number": 5,
    "arabicText": "إِيَّاكَ نَعۡبُدُ وَإِيَّاكَ نَسۡتَعِينُ",
    "arabicTextQpcV2": "ﱒ ﱓ ﱔ ﱕ",
    "translationText": "It is You we worship and You we ask for help.",
    "pageNumber": 1,
    "words": [
      {
        "id": 5334,
        "position": 1,
        "pageNumber": 1,
        "codeV2": "ﱒ",
        "textQpcHafs": "إِيَّاكَ",
        "charTypeName": "word"
      },
      {
        "id": 5335,
        "position": 2,
        "pageNumber": 1,
        "codeV2": "ﱓ",
        "textQpcHafs": "نَعۡبُدُ",
        "charTypeName": "word"
      },
      {
        "id": 5336,
        "position": 3,
        "pageNumber": 1,
        "codeV2": "ﱔ",
        "textQpcHafs": "وَإِيَّاكَ",
        "charTypeName": "word"
      },
      {
        "id": 5337,
        "position": 4,
        "pageNumber": 1,
        "codeV2": "ﱕ",
        "textQpcHafs": "نَسۡتَعِينُ",
        "charTypeName": "word"
      },
      {
        "id": 5338,
        "position": 5,
        "pageNumber": 1,
        "codeV2": "ﱖ",
        "textQpcHafs": "٥",
        "charTypeName": "end"
      }
    ]
  },
  {
    "number": 6,
    "arabicText": "ٱهۡدِنَا ٱلصِّرَٰطَ ٱلۡمُسۡتَقِيمَ",
    "arabicTextQpcV2": "ﱗ ﱘ ﱙ",
    "translationText": "Guide us to the straight path -",
    "pageNumber": 1,
    "words": [
      {
        "id": 6844,
        "position": 1,
        "pageNumber": 1,
        "codeV2": "ﱗ",
        "textQpcHafs": "ٱهۡدِنَا",
        "charTypeName": "word"
      },
      {
        "id": 6845,
        "position": 2,
        "pageNumber": 1,
        "codeV2": "ﱘ",
        "textQpcHafs": "ٱلصِّرَٰطَ",
        "charTypeName": "word"
      },
      {
        "id": 6846,
        "position": 3,
        "pageNumber": 1,
        "codeV2": "ﱙ",
        "textQpcHafs": "ٱلۡمُسۡتَقِيمَ",
        "charTypeName": "word"
      },
      {
        "id": 6847,
        "position": 4,
        "pageNumber": 1,
        "codeV2": "ﱚ",
        "textQpcHafs": "٦",
        "charTypeName": "end"
      }
    ]
  },
  {
    "number": 7,
    "arabicText": "صِرَٰطَ ٱلَّذِينَ أَنۡعَمۡتَ عَلَيۡهِمۡ غَيۡرِ ٱلۡمَغۡضُوبِ عَلَيۡهِمۡ وَلَا ٱلضَّآلِّينَ",
    "arabicTextQpcV2": "ﱛ ﱜ ﱝ ﱞ ﱟ ﱠ ﱡ ﱢ ﱣ",
    "translationText": "The path of those upon whom You have bestowed favor, not of those who have evoked [Your] anger or of those who are astray.",
    "pageNumber": 1,
    "words": [
      {
        "id": 8411,
        "position": 1,
        "pageNumber": 1,
        "codeV2": "ﱛ",
        "textQpcHafs": "صِرَٰطَ",
        "charTypeName": "word"
      },
      {
        "id": 8412,
        "position": 2,
        "pageNumber": 1,
        "codeV2": "ﱜ",
        "textQpcHafs": "ٱلَّذِينَ",
        "charTypeName": "word"
      },
      {
        "id": 8413,
        "position": 3,
        "pageNumber": 1,
        "codeV2": "ﱝ",
        "textQpcHafs": "أَنۡعَمۡتَ",
        "charTypeName": "word"
      },
      {
        "id": 8414,
        "position": 4,
        "pageNumber": 1,
        "codeV2": "ﱞ",
        "textQpcHafs": "عَلَيۡهِمۡ",
        "charTypeName": "word"
      },
      {
        "id": 8415,
        "position": 5,
        "pageNumber": 1,
        "codeV2": "ﱟ",
        "textQpcHafs": "غَيۡرِ",
        "charTypeName": "word"
      },
      {
        "id": 8416,
        "position": 6,
        "pageNumber": 1,
        "codeV2": "ﱠ",
        "textQpcHafs": "ٱلۡمَغۡضُوبِ",
        "charTypeName": "word"
      },
      {
        "id": 8417,
        "position": 7,
        "pageNumber": 1,
        "codeV2": "ﱡ",
        "textQpcHafs": "عَلَيۡهِمۡ",
        "charTypeName": "word"
      },
      {
        "id": 8418,
        "position": 8,
        "pageNumber": 1,
        "codeV2": "ﱢ",
        "textQpcHafs": "وَلَا",
        "charTypeName": "word"
      },
      {
        "id": 8419,
        "position": 9,
        "pageNumber": 1,
        "codeV2": "ﱣ",
        "textQpcHafs": "ٱلضَّآلِّينَ",
        "charTypeName": "word"
      },
      {
        "id": 8420,
        "position": 10,
        "pageNumber": 1,
        "codeV2": "ﱤ",
        "textQpcHafs": "٧",
        "charTypeName": "end"
      }
    ]
  }
] as VerseData[];
