/**
 * Script to fetch Al-Fatiha data from the API and save it as a hardcoded constant
 * Run with: npx tsx scripts/fetch-al-fatiha.ts
 */

const API_BASE = "http://localhost:3000/api/quran";
const SURAH_NUMBER = 1;
const FROM_AYAH = 1;
const TO_AYAH = 7;

async function fetchAlFatiha() {
  console.log("Fetching Al-Fatiha from API...");

  const verses = [];

  for (let ayah = FROM_AYAH; ayah <= TO_AYAH; ayah++) {
    const verseKey = `${SURAH_NUMBER}:${ayah}`;
    const params = new URLSearchParams({
      mushaf: "1", // QCF V2
      words: "true",
      word_fields: "code_v2,text_qpc_hafs,page_number",
      translations: "131", // Sahih International
    });

    const url = `${API_BASE}/verses/by_key/${verseKey}?${params}`;

    try {
      const response = await fetch(url);

      if (!response.ok) {
        throw new Error(`Failed to fetch ${verseKey}: ${response.status}`);
      }

      const data = await response.json();

      if (!data.verse) {
        throw new Error(`No verse data in response for ${verseKey}`);
      }

      verses.push(data.verse);
      console.log(`✓ Fetched verse ${verseKey}`);
    } catch (error) {
      console.error(`✗ Error fetching ${verseKey}:`, error);
      throw error;
    }
  }

  console.log(`\nSuccessfully fetched ${verses.length} verses`);

  // Known Al-Fatiha translations (Sahih International)
  // These are the exact translations from the API
  const knownTranslations = [
    "In the name of Allah, the Entirely Merciful, the Especially Merciful.",
    "All praise is due to Allah, Lord of the worlds -",
    "The Entirely Merciful, the Especially Merciful,",
    "Sovereign of the Day of Recompense.",
    "It is You we worship and You we ask for help.",
    "Guide us to the straight path -",
    "The path of those upon whom You have bestowed favor, not of those who have evoked [Your] anger or of those who are astray.",
  ];

  // Generate TypeScript file with the data
  const tsContent = `/**
 * Hardcoded Al-Fatiha data
 * Auto-generated by scripts/fetch-al-fatiha.ts
 * Last updated: ${new Date().toISOString()}
 *
 * This data is permanently cached so Al-Fatiha loads instantly without any API calls.
 * All other surahs use the normal API caching mechanism.
 */

import type { VerseData } from "@/types";

export const AL_FATIHA_VERSES: VerseData[] = ${JSON.stringify(verses.map((v, index) => {
    // Build translation from known translations or fall back to word-level translations
    const translationText = knownTranslations[index] || "";

    return {
      number: v.verse_number,
      arabicText: v.words?.filter((w: { char_type_name: string }) => w.char_type_name !== "end")
        .map((w: { text_qpc_hafs?: string }) => w.text_qpc_hafs || "")
        .join(" ") || "",
      arabicTextQpcV2: v.words?.filter((w: { char_type_name: string }) => w.char_type_name !== "end")
        .map((w: { code_v2?: string }) => w.code_v2 || "")
        .join(" ") || "",
      translationText,
      pageNumber: v.page_number,
      words: v.words?.map((w: {
        id?: number;
        position?: number;
        page_number?: number;
        code_v2?: string;
        text_qpc_hafs?: string;
        char_type_name?: string;
      }) => ({
        id: w.id,
        position: w.position,
        pageNumber: w.page_number || v.page_number,
        codeV2: w.code_v2,
        textQpcHafs: w.text_qpc_hafs,
        charTypeName: w.char_type_name,
      })) || [],
    };
  }), null, 2)} as VerseData[];
`;

  const fs = await import("fs");
  const path = await import("path");

  const outputPath = path.join(process.cwd(), "src", "lib", "alFatihaData.ts");
  fs.writeFileSync(outputPath, tsContent, "utf-8");

  console.log(`\n✓ Saved to: ${outputPath}`);
  console.log("\nNext steps:");
  console.log("1. Review the generated file");
  console.log("2. Run 'npm run build' to verify");
  console.log("3. The API will now use this hardcoded data for Al-Fatiha");
}

fetchAlFatiha().catch(console.error);
